# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Homework3' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Homework3
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'SDWebImage', '~>3.8'
  pod 'MBProgressHUD', '~>1.0.0'
  pod 'Alamofire', '~>3.4'
end
